[2022-10-28 01:24:32,293] [util.py:209]               [INFO]     |====================================================================================================|
[2022-10-28 01:24:32,293] [util.py:216]               [INFO]     |                                     ABC Collection in TV Shows                                     |
[2022-10-28 01:24:32,293] [util.py:220]               [INFO]     |====================================================================================================|
[2022-10-28 01:24:32,294] [plex_meta_manager.py:750]  [INFO]     |                                                                                                    |
[2022-10-28 01:24:32,294] [util.py:216]               [INFO]     |==================================== Validating ABC Attributes =====================================|
[2022-10-28 01:24:32,294] [builder.py:265]            [DEBUG]    |                                                                                                    |
[2022-10-28 01:24:32,294] [builder.py:266]            [DEBUG]    | Validating Method: template                                                                        |
[2022-10-28 01:24:32,295] [meta.py:83]                [DEBUG]    | Value: ordereddict([('name', 'network'), ('network', '2, 75, 2791'), ('poster', 'https://theposterdb.com/api/assets/193495')]) |
[2022-10-28 01:24:32,295] [builder.py:330]            [DEBUG]    |                                                                                                    |
[2022-10-28 01:24:32,295] [builder.py:331]            [DEBUG]    | Validating Method: sync_mode                                                                       |
[2022-10-28 01:24:32,295] [builder.py:335]            [DEBUG]    | Value: sync                                                                                        |
[2022-10-28 01:24:32,296] [builder.py:453]            [DEBUG]    |                                                                                                    |
[2022-10-28 01:24:32,296] [builder.py:454]            [DEBUG]    | Validating Method: collection_order                                                                |
[2022-10-28 01:24:32,296] [builder.py:455]            [DEBUG]    | Value: alpha                                                                                       |
[2022-10-28 01:24:32,296] [builder.py:472]            [DEBUG]    |                                                                                                    |
[2022-10-28 01:24:32,297] [builder.py:473]            [DEBUG]    | Validating Method: tmdb_network                                                                    |
[2022-10-28 01:24:32,297] [builder.py:474]            [DEBUG]    | Value: 2, 75, 2791                                                                                 |
[2022-10-28 01:24:32,672] [builder.py:472]            [DEBUG]    |                                                                                                    |
[2022-10-28 01:24:32,672] [builder.py:473]            [DEBUG]    | Validating Method: url_poster                                                                      |
[2022-10-28 01:24:32,672] [builder.py:474]            [DEBUG]    | Value: https://theposterdb.com/api/assets/193495                                                   |
[2022-10-28 01:24:32,673] [builder.py:472]            [DEBUG]    |                                                                                                    |
[2022-10-28 01:24:32,673] [builder.py:473]            [DEBUG]    | Validating Method: sort_title                                                                      |
[2022-10-28 01:24:32,673] [builder.py:474]            [DEBUG]    | Value: +2_ABC                                                                                      |
[2022-10-28 01:24:32,732] [builder.py:619]            [INFO]     |                                                                                                    |
[2022-10-28 01:24:32,733] [builder.py:620]            [INFO]     | Validation Successful                                                                              |
[2022-10-28 01:24:32,733] [plex_meta_manager.py:758]  [INFO]     |                                                                                                    |
[2022-10-28 01:24:32,734] [util.py:216]               [INFO]     |====================================== Running ABC Collection ======================================|
[2022-10-28 01:24:32,734] [plex_meta_manager.py:773]  [INFO]     |                                                                                                    |
[2022-10-28 01:24:32,734] [plex_meta_manager.py:774]  [INFO]     | Sync Mode: sync                                                                                    |
[2022-10-28 01:24:32,734] [builder.py:1275]           [DEBUG]    |                                                                                                    |
[2022-10-28 01:24:32,735] [builder.py:1276]           [DEBUG]    | Builder: tmdb_network: 2                                                                           |
[2022-10-28 01:24:32,735] [builder.py:1277]           [INFO]     |                                                                                                    |
[2022-10-28 01:24:33,282] [util.py:162]               [DEBUG]    | Traceback (most recent call last):                                                                 |
[2022-10-28 01:24:33,282] [util.py:162]               [DEBUG]    |   File "C:\Plex-Stack\Plex-Meta-Manager\pmm-venv\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen |
[2022-10-28 01:24:33,283] [util.py:162]               [DEBUG]    |     httplib_response = self._make_request(                                                         |
[2022-10-28 01:24:33,283] [util.py:162]               [DEBUG]    |   File "C:\Plex-Stack\Plex-Meta-Manager\pmm-venv\lib\site-packages\urllib3\connectionpool.py", line 398, in _make_request |
[2022-10-28 01:24:33,283] [util.py:162]               [DEBUG]    |     conn.request(method, url, **httplib_request_kw)                                                |
[2022-10-28 01:24:33,283] [util.py:162]               [DEBUG]    |   File "C:\Plex-Stack\Plex-Meta-Manager\pmm-venv\lib\site-packages\urllib3\connection.py", line 239, in request |
[2022-10-28 01:24:33,284] [util.py:162]               [DEBUG]    |     super(HTTPConnection, self).request(method, url, body=body, headers=headers)                   |
[2022-10-28 01:24:33,284] [util.py:162]               [DEBUG]    |   File "C:\Users\Jack\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1285, in request |
[2022-10-28 01:24:33,284] [util.py:162]               [DEBUG]    |     self._send_request(method, url, body, headers, encode_chunked)                                 |
[2022-10-28 01:24:33,284] [util.py:162]               [DEBUG]    |   File "C:\Users\Jack\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1331, in _send_request |
[2022-10-28 01:24:33,284] [util.py:162]               [DEBUG]    |     self.endheaders(body, encode_chunked=encode_chunked)                                           |
[2022-10-28 01:24:33,285] [util.py:162]               [DEBUG]    |   File "C:\Users\Jack\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1280, in endheaders |
[2022-10-28 01:24:33,285] [util.py:162]               [DEBUG]    |     self._send_output(message_body, encode_chunked=encode_chunked)                                 |
[2022-10-28 01:24:33,285] [util.py:162]               [DEBUG]    |   File "C:\Users\Jack\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1040, in _send_output |
[2022-10-28 01:24:33,285] [util.py:162]               [DEBUG]    |     self.send(msg)                                                                                 |
[2022-10-28 01:24:33,286] [util.py:162]               [DEBUG]    |   File "C:\Users\Jack\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1001, in send |
[2022-10-28 01:24:33,286] [util.py:162]               [DEBUG]    |     self.sock.sendall(data)                                                                        |
[2022-10-28 01:24:33,286] [util.py:162]               [DEBUG]    |   File "C:\Users\Jack\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1204, in sendall    |
[2022-10-28 01:24:33,286] [util.py:162]               [DEBUG]    |     v = self.send(byte_view[count:])                                                               |
[2022-10-28 01:24:33,287] [util.py:162]               [DEBUG]    |   File "C:\Users\Jack\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1173, in send       |
[2022-10-28 01:24:33,287] [util.py:162]               [DEBUG]    |     return self._sslobj.write(data)                                                                |
[2022-10-28 01:24:33,287] [util.py:162]               [DEBUG]    | ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host |
[2022-10-28 01:24:33,287] [util.py:162]               [DEBUG]    |                                                                                                    |
[2022-10-28 01:24:33,287] [util.py:162]               [DEBUG]    | During handling of the above exception, another exception occurred:                                |
[2022-10-28 01:24:33,288] [util.py:162]               [DEBUG]    |                                                                                                    |
[2022-10-28 01:24:33,288] [util.py:162]               [DEBUG]    | Traceback (most recent call last):                                                                 |
[2022-10-28 01:24:33,288] [util.py:162]               [DEBUG]    |   File "C:\Plex-Stack\Plex-Meta-Manager\pmm-venv\lib\site-packages\requests\adapters.py", line 440, in send |
[2022-10-28 01:24:33,288] [util.py:162]               [DEBUG]    |     resp = conn.urlopen(                                                                           |
[2022-10-28 01:24:33,289] [util.py:162]               [DEBUG]    |   File "C:\Plex-Stack\Plex-Meta-Manager\pmm-venv\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen |
[2022-10-28 01:24:33,289] [util.py:162]               [DEBUG]    |     retries = retries.increment(                                                                   |
[2022-10-28 01:24:33,289] [util.py:162]               [DEBUG]    |   File "C:\Plex-Stack\Plex-Meta-Manager\pmm-venv\lib\site-packages\urllib3\util\retry.py", line 550, in increment |
[2022-10-28 01:24:33,289] [util.py:162]               [DEBUG]    |     raise six.reraise(type(error), error, _stacktrace)                                             |
[2022-10-28 01:24:33,289] [util.py:162]               [DEBUG]    |   File "C:\Plex-Stack\Plex-Meta-Manager\pmm-venv\lib\site-packages\urllib3\packages\six.py", line 769, in reraise |
[2022-10-28 01:24:33,290] [util.py:162]               [DEBUG]    |     raise value.with_traceback(tb)                                                                 |
[2022-10-28 01:24:33,290] [util.py:162]               [DEBUG]    |   File "C:\Plex-Stack\Plex-Meta-Manager\pmm-venv\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen |
[2022-10-28 01:24:33,290] [util.py:162]               [DEBUG]    |     httplib_response = self._make_request(                                                         |
[2022-10-28 01:24:33,290] [util.py:162]               [DEBUG]    |   File "C:\Plex-Stack\Plex-Meta-Manager\pmm-venv\lib\site-packages\urllib3\connectionpool.py", line 398, in _make_request |
[2022-10-28 01:24:33,291] [util.py:162]               [DEBUG]    |     conn.request(method, url, **httplib_request_kw)                                                |
[2022-10-28 01:24:33,291] [util.py:162]               [DEBUG]    |   File "C:\Plex-Stack\Plex-Meta-Manager\pmm-venv\lib\site-packages\urllib3\connection.py", line 239, in request |
[2022-10-28 01:24:33,291] [util.py:162]               [DEBUG]    |     super(HTTPConnection, self).request(method, url, body=body, headers=headers)                   |
[2022-10-28 01:24:33,291] [util.py:162]               [DEBUG]    |   File "C:\Users\Jack\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1285, in request |
[2022-10-28 01:24:33,291] [util.py:162]               [DEBUG]    |     self._send_request(method, url, body, headers, encode_chunked)                                 |
[2022-10-28 01:24:33,292] [util.py:162]               [DEBUG]    |   File "C:\Users\Jack\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1331, in _send_request |
[2022-10-28 01:24:33,292] [util.py:162]               [DEBUG]    |     self.endheaders(body, encode_chunked=encode_chunked)                                           |
[2022-10-28 01:24:33,292] [util.py:162]               [DEBUG]    |   File "C:\Users\Jack\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1280, in endheaders |
[2022-10-28 01:24:33,292] [util.py:162]               [DEBUG]    |     self._send_output(message_body, encode_chunked=encode_chunked)                                 |
[2022-10-28 01:24:33,293] [util.py:162]               [DEBUG]    |   File "C:\Users\Jack\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1040, in _send_output |
[2022-10-28 01:24:33,293] [util.py:162]               [DEBUG]    |     self.send(msg)                                                                                 |
[2022-10-28 01:24:33,293] [util.py:162]               [DEBUG]    |   File "C:\Users\Jack\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1001, in send |
[2022-10-28 01:24:33,293] [util.py:162]               [DEBUG]    |     self.sock.sendall(data)                                                                        |
[2022-10-28 01:24:33,293] [util.py:162]               [DEBUG]    |   File "C:\Users\Jack\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1204, in sendall    |
[2022-10-28 01:24:33,294] [util.py:162]               [DEBUG]    |     v = self.send(byte_view[count:])                                                               |
[2022-10-28 01:24:33,294] [util.py:162]               [DEBUG]    |   File "C:\Users\Jack\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1173, in send       |
[2022-10-28 01:24:33,294] [util.py:162]               [DEBUG]    |     return self._sslobj.write(data)                                                                |
[2022-10-28 01:24:33,294] [util.py:162]               [DEBUG]    | urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)) |
[2022-10-28 01:24:33,295] [util.py:162]               [DEBUG]    |                                                                                                    |
[2022-10-28 01:24:33,295] [util.py:162]               [DEBUG]    | During handling of the above exception, another exception occurred:                                |
[2022-10-28 01:24:33,295] [util.py:162]               [DEBUG]    |                                                                                                    |
[2022-10-28 01:24:33,295] [util.py:162]               [DEBUG]    | Traceback (most recent call last):                                                                 |
[2022-10-28 01:24:33,295] [util.py:162]               [DEBUG]    |   File "C:\Plex-Stack\Plex-Meta-Manager\plex_meta_manager.py", line 783, in run_collection         |
[2022-10-28 01:24:33,296] [util.py:162]               [DEBUG]    |     builder.find_rating_keys()                                                                     |
[2022-10-28 01:24:33,296] [util.py:162]               [DEBUG]    |   File "C:\Plex-Stack\Plex-Meta-Manager\modules\builder.py", line 1279, in find_rating_keys        |
[2022-10-28 01:24:33,296] [util.py:162]               [DEBUG]    |     ids = self.gather_ids(method, value)                                                           |
[2022-10-28 01:24:33,297] [util.py:162]               [DEBUG]    |   File "C:\Plex-Stack\Plex-Meta-Manager\modules\builder.py", line 1267, in gather_ids              |
[2022-10-28 01:24:33,297] [util.py:162]               [DEBUG]    |     return self.config.TMDb.get_tmdb_ids(method, value, self.library.is_movie)                     |
[2022-10-28 01:24:33,297] [util.py:162]               [DEBUG]    |   File "C:\Plex-Stack\Plex-Meta-Manager\modules\tmdb.py", line 278, in get_tmdb_ids                |
[2022-10-28 01:24:33,297] [util.py:162]               [DEBUG]    |     ids, amount = self._discover(attrs, limit, is_movie)                                           |
[2022-10-28 01:24:33,297] [util.py:162]               [DEBUG]    |   File "C:\Plex-Stack\Plex-Meta-Manager\modules\tmdb.py", line 225, in _discover                   |
[2022-10-28 01:24:33,298] [util.py:162]               [DEBUG]    |     tmdb_items = self.Discover.discover_movies(attrs) if is_movie else self.Discover.discover_tv_shows(attrs) |
[2022-10-28 01:24:33,298] [util.py:162]               [DEBUG]    |   File "C:\Plex-Stack\Plex-Meta-Manager\pmm-venv\lib\site-packages\tmdbv3api\objs\discover.py", line 27, in discover_tv_shows |
[2022-10-28 01:24:33,298] [util.py:162]               [DEBUG]    |     return self._get_obj(self._call(self._urls["tv"], urlencode(params)))                          |
[2022-10-28 01:24:33,298] [util.py:162]               [DEBUG]    |   File "C:\Plex-Stack\Plex-Meta-Manager\pmm-venv\lib\site-packages\tmdbv3api\tmdb.py", line 131, in _call |
[2022-10-28 01:24:33,298] [util.py:162]               [DEBUG]    |     req = self.cached_request(method, url, data)                                                   |
[2022-10-28 01:24:33,299] [util.py:162]               [DEBUG]    |   File "C:\Plex-Stack\Plex-Meta-Manager\pmm-venv\lib\site-packages\tmdbv3api\tmdb.py", line 111, in cached_request |
[2022-10-28 01:24:33,299] [util.py:162]               [DEBUG]    |     return requests.request(method, url, data=data)                                                |
[2022-10-28 01:24:33,299] [util.py:162]               [DEBUG]    |   File "C:\Plex-Stack\Plex-Meta-Manager\pmm-venv\lib\site-packages\requests\api.py", line 61, in request |
[2022-10-28 01:24:33,299] [util.py:162]               [DEBUG]    |     return session.request(method=method, url=url, **kwargs)                                       |
[2022-10-28 01:24:33,299] [util.py:162]               [DEBUG]    |   File "C:\Plex-Stack\Plex-Meta-Manager\pmm-venv\lib\site-packages\requests\sessions.py", line 529, in request |
[2022-10-28 01:24:33,300] [util.py:162]               [DEBUG]    |     resp = self.send(prep, **send_kwargs)                                                          |
[2022-10-28 01:24:33,300] [util.py:162]               [DEBUG]    |   File "C:\Plex-Stack\Plex-Meta-Manager\pmm-venv\lib\site-packages\requests\sessions.py", line 645, in send |
[2022-10-28 01:24:33,300] [util.py:162]               [DEBUG]    |     r = adapter.send(request, **kwargs)                                                            |
[2022-10-28 01:24:33,300] [util.py:162]               [DEBUG]    |   File "C:\Plex-Stack\Plex-Meta-Manager\pmm-venv\lib\site-packages\requests\adapters.py", line 501, in send |
[2022-10-28 01:24:33,300] [util.py:162]               [DEBUG]    |     raise ConnectionError(err, request=request)                                                    |
[2022-10-28 01:24:33,301] [util.py:162]               [DEBUG]    | requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)) |
[2022-10-28 01:24:33,301] [util.py:162]               [DEBUG]    |                                                                                                    |
[2022-10-28 01:24:33,301] [plex_meta_manager.py:877]  [ERROR]    | Unknown Error: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)) |
[2022-10-28 01:24:33,301] [plex_meta_manager.py:880]  [INFO]     |                                                                                                    |
[2022-10-28 01:24:33,302] [util.py:209]               [INFO]     |====================================================================================================|
[2022-10-28 01:24:33,302] [util.py:216]               [INFO]     |                                      Finished ABC Collection                                       |
[2022-10-28 01:24:33,302] [util.py:216]               [INFO]     |                                    Collection Run Time: 0:00:01                                    |
[2022-10-28 01:24:33,303] [util.py:220]               [INFO]     |====================================================================================================|
