[2022-11-05 19:21:06,754] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-05 19:21:06,755] [plex_meta_manager.py:134]  [INFO]     |                                                                                                    |
[2022-11-05 19:21:06,755] [plex_meta_manager.py:135]  [INFO]     |        ____  _             __  __      _          __  __                                           |
[2022-11-05 19:21:06,756] [plex_meta_manager.py:136]  [INFO]     |       |  _ \| | _____  __ |  \/  | ___| |_ __ _  |  \/  | __ _ _ __   __ _  __ _  ___ _ __         |
[2022-11-05 19:21:06,756] [plex_meta_manager.py:137]  [INFO]     |       | |_) | |/ _ \ \/ / | |\/| |/ _ \ __/ _` | | |\/| |/ _` | '_ \ / _` |/ _` |/ _ \ '__|        |
[2022-11-05 19:21:06,757] [plex_meta_manager.py:138]  [INFO]     |       |  __/| |  __/>  <  | |  | |  __/ || (_| | | |  | | (_| | | | | (_| | (_| |  __/ |           |
[2022-11-05 19:21:06,757] [plex_meta_manager.py:139]  [INFO]     |       |_|   |_|\___/_/\_\ |_|  |_|\___|\__\__,_| |_|  |_|\__,_|_| |_|\__,_|\__, |\___|_|           |
[2022-11-05 19:21:06,757] [plex_meta_manager.py:140]  [INFO]     |                                                                            |___/                   |
[2022-11-05 19:21:06,758] [plex_meta_manager.py:141]  [INFO]     |     Version: 1.15.0                                                                                |
[2022-11-05 19:21:06,758] [util.py:207]               [DEBUG]    |====================================================================================================|
[2022-11-05 19:21:06,758] [plex_meta_manager.py:152]  [DEBUG]    | --config (PMM_CONFIG): None                                                                        |
[2022-11-05 19:21:06,758] [plex_meta_manager.py:153]  [DEBUG]    | --time (PMM_TIME): 03:00                                                                           |
[2022-11-05 19:21:06,758] [plex_meta_manager.py:154]  [DEBUG]    | --run (PMM_RUN): True                                                                              |
[2022-11-05 19:21:06,758] [plex_meta_manager.py:155]  [DEBUG]    | --run-tests (PMM_TEST): False                                                                      |
[2022-11-05 19:21:06,759] [plex_meta_manager.py:156]  [DEBUG]    | --collections-only (PMM_COLLECTIONS_ONLY): False                                                   |
[2022-11-05 19:21:06,759] [plex_meta_manager.py:157]  [DEBUG]    | --libraries-only (PMM_LIBRARIES_ONLY): False                                                       |
[2022-11-05 19:21:06,759] [plex_meta_manager.py:158]  [DEBUG]    | --libraries-first (PMM_LIBRARIES_FIRST): False                                                     |
[2022-11-05 19:21:06,759] [plex_meta_manager.py:159]  [DEBUG]    | --run-collections (PMM_COLLECTIONS): None                                                          |
[2022-11-05 19:21:06,759] [plex_meta_manager.py:160]  [DEBUG]    | --run-libraries (PMM_LIBRARIES): None                                                              |
[2022-11-05 19:21:06,759] [plex_meta_manager.py:161]  [DEBUG]    | --ignore-schedules (PMM_IGNORE_SCHEDULES): False                                                   |
[2022-11-05 19:21:06,759] [plex_meta_manager.py:162]  [DEBUG]    | --delete-collections (PMM_DELETE_COLLECTIONS): False                                               |
[2022-11-05 19:21:06,759] [plex_meta_manager.py:163]  [DEBUG]    | --resume (PMM_RESUME): None                                                                        |
[2022-11-05 19:21:06,759] [plex_meta_manager.py:164]  [DEBUG]    | --no-countdown (PMM_NO_COUNTDOWN): False                                                           |
[2022-11-05 19:21:06,760] [plex_meta_manager.py:165]  [DEBUG]    | --no-missing (PMM_NO_MISSING): False                                                               |
[2022-11-05 19:21:06,760] [plex_meta_manager.py:166]  [DEBUG]    | --read-only-config (PMM_READ_ONLY_CONFIG): False                                                   |
[2022-11-05 19:21:06,760] [plex_meta_manager.py:167]  [DEBUG]    | --divider (PMM_DIVIDER): =                                                                         |
[2022-11-05 19:21:06,760] [plex_meta_manager.py:168]  [DEBUG]    | --width (PMM_WIDTH): 100                                                                           |
[2022-11-05 19:21:06,760] [plex_meta_manager.py:169]  [DEBUG]    | --debug (PMM_DEBUG): False                                                                         |
[2022-11-05 19:21:06,760] [plex_meta_manager.py:170]  [DEBUG]    | --trace (PMM_TRACE): False                                                                         |
[2022-11-05 19:21:06,760] [plex_meta_manager.py:171]  [DEBUG]    |                                                                                                    |
[2022-11-05 19:21:06,761] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-05 19:21:06,761] [util.py:216]               [INFO]     |                                            Starting Run                                            |
[2022-11-05 19:21:06,761] [util.py:220]               [INFO]     |====================================================================================================|
[2022-11-05 19:21:06,761] [config.py:37]              [INFO]     | Locating config...                                                                                 |
[2022-11-05 19:21:06,762] [config.py:43]              [INFO]     | Using C:\Plex-Stack\Plex-Meta-Manager\config\config.yml as config                                  |
[2022-11-05 19:21:06,797] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-05 19:21:06,798] [cache.py:17]               [INFO]     | Initializing cache database at C:\Plex-Stack\Plex-Meta-Manager\config\config.cache                 |
[2022-11-05 19:21:06,799] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-05 19:21:06,799] [config.py:313]             [INFO]     | Connecting to Notifiarr...                                                                         |
[2022-11-05 19:21:06,800] [util.py:162]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "C:\Plex-Stack\Plex-Meta-Manager\modules\config.py", line 316, in __init__
                                                                 |     "apikey": check_for_attribute(self.data, "apikey", parent="notifiarr", throw=True),
                                                                 |   File "C:\Plex-Stack\Plex-Meta-Manager\modules\config.py", line 251, in check_for_attribute
                                                                 |     raise Failed(f"Config Error: {message}")
                                                                 | modules.util.Failed: Config Error: notifiarr sub-attribute apikey is blank
                                                                 | 
[2022-11-05 19:21:06,801] [config.py:322]             [ERROR]    | Config Error: notifiarr sub-attribute apikey is blank
[2022-11-05 19:21:06,801] [config.py:323]             [INFO]     | Notifiarr Connection Failed
[2022-11-05 19:21:06,802] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-05 19:21:06,802] [config.py:341]             [INFO]     | Connecting to TMDb...                                                                              |
[2022-11-05 19:21:06,853] [config.py:346]             [INFO]     | TMDb Connection Successful                                                                         |
[2022-11-05 19:21:06,854] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-05 19:21:06,854] [config.py:354]             [INFO]     | Connecting to OMDb...                                                                              |
[2022-11-05 19:21:06,855] [config.py:359]             [ERROR]    | Config Error: omdb sub-attribute apikey is blank                                                   |
[2022-11-05 19:21:06,855] [config.py:360]             [INFO]     | OMDb Connection Failed                                                                             |
[2022-11-05 19:21:06,856] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-05 19:21:06,856] [config.py:368]             [INFO]     | Connecting to Trakt...                                                                             |
[2022-11-05 19:21:06,986] [config.py:379]             [INFO]     | Trakt Connection Successful                                                                        |
[2022-11-05 19:21:06,986] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-05 19:21:06,987] [config.py:387]             [INFO]     | Connecting to My Anime List...                                                                     |
[2022-11-05 19:21:07,116] [mal.py:95]                 [DEBUG]    | MyAnimeList Error: invalid_token                                                                   |
[2022-11-05 19:21:07,117] [mal.py:100]                [INFO]     | Refreshing Access Token...                                                                         |
[2022-11-05 19:21:08,271] [mal.py:122]                [INFO]     | Saving authorization information to C:\Plex-Stack\Plex-Meta-Manager\config\config.yml              |
[2022-11-05 19:21:08,279] [config.py:398]             [INFO]     | My Anime List Connection Successful                                                                |
[2022-11-05 19:21:08,279] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-05 19:21:08,280] [config.py:405]             [INFO]     | Connecting to AniDB...                                                                             |
[2022-11-05 19:21:08,935] [config.py:413]             [ERROR]    | AniDB Error: Login failed                                                                          |
[2022-11-05 19:21:26,447] [config.py:414]             [INFO]     | My Anime List Connection Successful                                                                |
[2022-11-05 19:21:26,449] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-05 19:21:26,449] [config.py:466]             [WARNING]  | playlist_files attribute not found                                                                 |
[2022-11-05 19:21:26,450] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-05 19:21:26,450] [config.py:486]             [INFO]     | Connecting to Plex Libraries...                                                                    |
[2022-11-05 19:21:26,451] [util.py:162]               [DEBUG]    | Config Warning: sonarr sub-attribute monitor: False is an invalid input using all as default       |
[2022-11-05 19:21:26,451] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-05 19:21:26,451] [util.py:216]               [INFO]     |                                        Movies Configuration                                        |
[2022-11-05 19:21:26,452] [util.py:220]               [INFO]     |====================================================================================================|
[2022-11-05 19:21:26,452] [config.py:553]             [INFO]     |                                                                                                    |
[2022-11-05 19:21:26,453] [config.py:554]             [INFO]     | Connecting to Movies Library...                                                                    |
[2022-11-05 19:21:26,453] [util.py:162]               [DEBUG]    | Config Warning: missing_path attribute not found using None as default                             |
[2022-11-05 19:21:26,455] [meta.py:227]               [INFO]     | 
[2022-11-05 19:21:26,455] [meta.py:228]               [INFO]     | Loading Metadata File: config/Movie.yml
[2022-11-05 19:21:26,511] [meta.py:236]               [INFO]     | Metadata File Loaded Successfully
[2022-11-05 19:21:26,512] [meta.py:227]               [INFO]     | 
[2022-11-05 19:21:26,513] [meta.py:228]               [INFO]     | Loading Metadata File: config/Genre.yml
[2022-11-05 19:21:26,568] [meta.py:236]               [INFO]     | Metadata File Loaded Successfully
[2022-11-05 19:21:26,568] [meta.py:227]               [INFO]     | 
[2022-11-05 19:21:26,569] [meta.py:228]               [INFO]     | Loading Metadata File: config/Special_Genre.yml
[2022-11-05 19:21:26,579] [meta.py:236]               [INFO]     | Metadata File Loaded Successfully
[2022-11-05 19:21:26,580] [meta.py:227]               [INFO]     | 
[2022-11-05 19:21:26,580] [meta.py:228]               [INFO]     | Loading Metadata File: config/Studio.yml
[2022-11-05 19:21:26,599] [meta.py:236]               [INFO]     | Metadata File Loaded Successfully
[2022-11-05 19:21:26,599] [meta.py:227]               [INFO]     | 
[2022-11-05 19:21:26,600] [meta.py:228]               [INFO]     | Loading Metadata File: config/Holiday.yml
[2022-11-05 19:21:26,625] [meta.py:236]               [INFO]     | Metadata File Loaded Successfully
[2022-11-05 19:21:26,626] [meta.py:227]               [INFO]     | 
[2022-11-05 19:21:26,627] [meta.py:228]               [INFO]     | Loading Metadata File: config/Metadata.yml
[2022-11-05 19:21:26,670] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-05 19:21:26,670] [util.py:216]               [INFO]     |                                     Exiting Plex Meta Manager                                      |
[2022-11-05 19:21:26,671] [util.py:220]               [INFO]     |====================================================================================================|
