[2022-11-05 19:21:28,257] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-05 19:21:28,258] [plex_meta_manager.py:134]  [INFO]     |                                                                                                    |
[2022-11-05 19:21:28,258] [plex_meta_manager.py:135]  [INFO]     |        ____  _             __  __      _          __  __                                           |
[2022-11-05 19:21:28,259] [plex_meta_manager.py:136]  [INFO]     |       |  _ \| | _____  __ |  \/  | ___| |_ __ _  |  \/  | __ _ _ __   __ _  __ _  ___ _ __         |
[2022-11-05 19:21:28,259] [plex_meta_manager.py:137]  [INFO]     |       | |_) | |/ _ \ \/ / | |\/| |/ _ \ __/ _` | | |\/| |/ _` | '_ \ / _` |/ _` |/ _ \ '__|        |
[2022-11-05 19:21:28,259] [plex_meta_manager.py:138]  [INFO]     |       |  __/| |  __/>  <  | |  | |  __/ || (_| | | |  | | (_| | | | | (_| | (_| |  __/ |           |
[2022-11-05 19:21:28,260] [plex_meta_manager.py:139]  [INFO]     |       |_|   |_|\___/_/\_\ |_|  |_|\___|\__\__,_| |_|  |_|\__,_|_| |_|\__,_|\__, |\___|_|           |
[2022-11-05 19:21:28,260] [plex_meta_manager.py:140]  [INFO]     |                                                                            |___/                   |
[2022-11-05 19:21:28,260] [plex_meta_manager.py:141]  [INFO]     |     Version: 1.15.0                                                                                |
[2022-11-05 19:21:28,261] [util.py:207]               [DEBUG]    |====================================================================================================|
[2022-11-05 19:21:28,261] [plex_meta_manager.py:152]  [DEBUG]    | --config (PMM_CONFIG): None                                                                        |
[2022-11-05 19:21:28,261] [plex_meta_manager.py:153]  [DEBUG]    | --time (PMM_TIME): 03:00                                                                           |
[2022-11-05 19:21:28,261] [plex_meta_manager.py:154]  [DEBUG]    | --run (PMM_RUN): True                                                                              |
[2022-11-05 19:21:28,261] [plex_meta_manager.py:155]  [DEBUG]    | --run-tests (PMM_TEST): False                                                                      |
[2022-11-05 19:21:28,261] [plex_meta_manager.py:156]  [DEBUG]    | --collections-only (PMM_COLLECTIONS_ONLY): False                                                   |
[2022-11-05 19:21:28,261] [plex_meta_manager.py:157]  [DEBUG]    | --libraries-only (PMM_LIBRARIES_ONLY): False                                                       |
[2022-11-05 19:21:28,262] [plex_meta_manager.py:158]  [DEBUG]    | --libraries-first (PMM_LIBRARIES_FIRST): False                                                     |
[2022-11-05 19:21:28,262] [plex_meta_manager.py:159]  [DEBUG]    | --run-collections (PMM_COLLECTIONS): None                                                          |
[2022-11-05 19:21:28,262] [plex_meta_manager.py:160]  [DEBUG]    | --run-libraries (PMM_LIBRARIES): None                                                              |
[2022-11-05 19:21:28,262] [plex_meta_manager.py:161]  [DEBUG]    | --ignore-schedules (PMM_IGNORE_SCHEDULES): False                                                   |
[2022-11-05 19:21:28,262] [plex_meta_manager.py:162]  [DEBUG]    | --delete-collections (PMM_DELETE_COLLECTIONS): False                                               |
[2022-11-05 19:21:28,262] [plex_meta_manager.py:163]  [DEBUG]    | --resume (PMM_RESUME): None                                                                        |
[2022-11-05 19:21:28,262] [plex_meta_manager.py:164]  [DEBUG]    | --no-countdown (PMM_NO_COUNTDOWN): False                                                           |
[2022-11-05 19:21:28,263] [plex_meta_manager.py:165]  [DEBUG]    | --no-missing (PMM_NO_MISSING): False                                                               |
[2022-11-05 19:21:28,263] [plex_meta_manager.py:166]  [DEBUG]    | --read-only-config (PMM_READ_ONLY_CONFIG): False                                                   |
[2022-11-05 19:21:28,263] [plex_meta_manager.py:167]  [DEBUG]    | --divider (PMM_DIVIDER): =                                                                         |
[2022-11-05 19:21:28,263] [plex_meta_manager.py:168]  [DEBUG]    | --width (PMM_WIDTH): 100                                                                           |
[2022-11-05 19:21:28,263] [plex_meta_manager.py:169]  [DEBUG]    | --debug (PMM_DEBUG): False                                                                         |
[2022-11-05 19:21:28,263] [plex_meta_manager.py:170]  [DEBUG]    | --trace (PMM_TRACE): False                                                                         |
[2022-11-05 19:21:28,263] [plex_meta_manager.py:171]  [DEBUG]    |                                                                                                    |
[2022-11-05 19:21:28,263] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-05 19:21:28,264] [util.py:216]               [INFO]     |                                            Starting Run                                            |
[2022-11-05 19:21:28,264] [util.py:220]               [INFO]     |====================================================================================================|
[2022-11-05 19:21:28,264] [config.py:37]              [INFO]     | Locating config...                                                                                 |
[2022-11-05 19:21:28,265] [config.py:43]              [INFO]     | Using C:\Plex-Stack\Plex-Meta-Manager\config\config.yml as config                                  |
[2022-11-05 19:21:28,301] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-05 19:21:28,302] [cache.py:17]               [INFO]     | Initializing cache database at C:\Plex-Stack\Plex-Meta-Manager\config\config.cache                 |
[2022-11-05 19:21:28,303] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-05 19:21:28,304] [config.py:313]             [INFO]     | Connecting to Notifiarr...                                                                         |
[2022-11-05 19:21:28,304] [util.py:162]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "C:\Plex-Stack\Plex-Meta-Manager\modules\config.py", line 316, in __init__
                                                                 |     "apikey": check_for_attribute(self.data, "apikey", parent="notifiarr", throw=True),
                                                                 |   File "C:\Plex-Stack\Plex-Meta-Manager\modules\config.py", line 251, in check_for_attribute
                                                                 |     raise Failed(f"Config Error: {message}")
                                                                 | modules.util.Failed: Config Error: notifiarr sub-attribute apikey is blank
                                                                 | 
[2022-11-05 19:21:28,305] [config.py:322]             [ERROR]    | Config Error: notifiarr sub-attribute apikey is blank
[2022-11-05 19:21:28,306] [config.py:323]             [INFO]     | Notifiarr Connection Failed
[2022-11-05 19:21:28,306] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-05 19:21:28,306] [config.py:341]             [INFO]     | Connecting to TMDb...                                                                              |
[2022-11-05 19:21:28,361] [config.py:346]             [INFO]     | TMDb Connection Successful                                                                         |
[2022-11-05 19:21:28,361] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-05 19:21:28,362] [config.py:354]             [INFO]     | Connecting to OMDb...                                                                              |
[2022-11-05 19:21:28,363] [config.py:359]             [ERROR]    | Config Error: omdb sub-attribute apikey is blank                                                   |
[2022-11-05 19:21:28,363] [config.py:360]             [INFO]     | OMDb Connection Failed                                                                             |
[2022-11-05 19:21:28,363] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-05 19:21:28,364] [config.py:368]             [INFO]     | Connecting to Trakt...                                                                             |
[2022-11-05 19:21:28,478] [config.py:379]             [INFO]     | Trakt Connection Successful                                                                        |
[2022-11-05 19:21:28,479] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-05 19:21:28,480] [config.py:387]             [INFO]     | Connecting to My Anime List...                                                                     |
[2022-11-05 19:21:28,785] [config.py:398]             [INFO]     | My Anime List Connection Successful                                                                |
[2022-11-05 19:21:28,786] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-05 19:21:28,786] [config.py:405]             [INFO]     | Connecting to AniDB...                                                                             |
[2022-11-05 19:21:29,415] [config.py:413]             [ERROR]    | AniDB Error: Login failed                                                                          |
[2022-11-05 19:21:29,415] [config.py:414]             [INFO]     | My Anime List Connection Successful                                                                |
[2022-11-05 19:21:29,416] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-05 19:21:29,416] [config.py:466]             [WARNING]  | playlist_files attribute not found                                                                 |
[2022-11-05 19:21:29,417] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-05 19:21:29,417] [config.py:486]             [INFO]     | Connecting to Plex Libraries...                                                                    |
[2022-11-05 19:21:29,417] [util.py:162]               [DEBUG]    | Config Warning: sonarr sub-attribute monitor: False is an invalid input using all as default       |
[2022-11-05 19:21:29,418] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-05 19:21:29,418] [util.py:216]               [INFO]     |                                        Movies Configuration                                        |
[2022-11-05 19:21:29,418] [util.py:220]               [INFO]     |====================================================================================================|
[2022-11-05 19:21:29,419] [config.py:553]             [INFO]     |                                                                                                    |
[2022-11-05 19:21:29,419] [config.py:554]             [INFO]     | Connecting to Movies Library...                                                                    |
[2022-11-05 19:21:29,419] [util.py:162]               [DEBUG]    | Config Warning: missing_path attribute not found using None as default                             |
[2022-11-05 19:21:29,420] [meta.py:227]               [INFO]     | 
[2022-11-05 19:21:29,420] [meta.py:228]               [INFO]     | Loading Metadata File: config/Movie.yml
[2022-11-05 19:21:29,473] [meta.py:236]               [INFO]     | Metadata File Loaded Successfully
[2022-11-05 19:21:29,473] [meta.py:227]               [INFO]     | 
[2022-11-05 19:21:29,474] [meta.py:228]               [INFO]     | Loading Metadata File: config/Genre.yml
[2022-11-05 19:21:29,518] [meta.py:236]               [INFO]     | Metadata File Loaded Successfully
[2022-11-05 19:21:29,519] [meta.py:227]               [INFO]     | 
[2022-11-05 19:21:29,520] [meta.py:228]               [INFO]     | Loading Metadata File: config/Special_Genre.yml
[2022-11-05 19:21:29,530] [meta.py:236]               [INFO]     | Metadata File Loaded Successfully
[2022-11-05 19:21:29,530] [meta.py:227]               [INFO]     | 
[2022-11-05 19:21:29,530] [meta.py:228]               [INFO]     | Loading Metadata File: config/Studio.yml
[2022-11-05 19:21:29,550] [meta.py:236]               [INFO]     | Metadata File Loaded Successfully
[2022-11-05 19:21:29,551] [meta.py:227]               [INFO]     | 
[2022-11-05 19:21:29,551] [meta.py:228]               [INFO]     | Loading Metadata File: config/Holiday.yml
[2022-11-05 19:21:29,578] [meta.py:236]               [INFO]     | Metadata File Loaded Successfully
[2022-11-05 19:21:29,578] [meta.py:227]               [INFO]     | 
[2022-11-05 19:21:29,579] [meta.py:228]               [INFO]     | Loading Metadata File: config/Metadata.yml
[2022-11-05 19:21:30,468] [meta.py:236]               [INFO]     | Metadata File Loaded Successfully
[2022-11-05 19:21:30,469] [meta.py:227]               [INFO]     | 
[2022-11-05 19:21:30,469] [meta.py:228]               [INFO]     | Loading Metadata File: config/Overlays.yml
[2022-11-05 19:21:30,473] [meta.py:236]               [INFO]     | Metadata File Loaded Successfully
[2022-11-05 19:21:30,473] [library.py:123]            [INFO]     | 
[2022-11-05 19:21:30,474] [library.py:125]            [INFO]     | Using Asset Directory: config/assets
[2022-11-05 19:21:30,474] [plex.py:386]               [INFO]     | 
[2022-11-05 19:21:30,481] [config.py:748]             [INFO]     | Movies Library Connection Successful
[2022-11-05 19:21:30,481] [config.py:758]             [INFO]     | 
[2022-11-05 19:21:30,482] [util.py:216]               [INFO]     |======================================= Radarr Configuration =======================================|
[2022-11-05 19:21:30,482] [config.py:760]             [INFO]     |                                                                                                    |
[2022-11-05 19:21:30,482] [config.py:761]             [INFO]     | Connecting to Movies library's Radarr...                                                           |
[2022-11-05 19:21:30,483] [config.py:762]             [INFO]     |                                                                                                    |
[2022-11-05 19:21:30,505] [config.py:783]             [INFO]     | Movies library's Radarr Connection Successful                                                      |
[2022-11-05 19:21:30,505] [config.py:786]             [INFO]     |                                                                                                    |
[2022-11-05 19:21:30,506] [util.py:216]               [INFO]     |======================================= Sonarr Configuration =======================================|
[2022-11-05 19:21:30,507] [config.py:788]             [INFO]     |                                                                                                    |
[2022-11-05 19:21:30,507] [config.py:789]             [INFO]     | Connecting to Movies library's Sonarr...                                                           |
[2022-11-05 19:21:30,507] [config.py:790]             [INFO]     |                                                                                                    |
[2022-11-05 19:21:30,521] [config.py:814]             [INFO]     | Movies library's Sonarr Connection Successful                                                      |
[2022-11-05 19:21:30,522] [config.py:817]             [INFO]     |                                                                                                    |
[2022-11-05 19:21:30,522] [util.py:216]               [INFO]     |====================================== Tautulli Configuration ======================================|
[2022-11-05 19:21:30,522] [config.py:819]             [INFO]     |                                                                                                    |
[2022-11-05 19:21:30,522] [config.py:820]             [INFO]     | Connecting to Movies library's Tautulli...                                                         |
[2022-11-05 19:21:30,523] [config.py:821]             [INFO]     |                                                                                                    |
[2022-11-05 19:21:30,523] [tautulli.py:74]            [DEBUG]    | Tautulli URL: URL/api/v2?apikey=APIKEY&cmd=get_library_names                                       |
[2022-11-05 19:23:30,169] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-05 19:23:30,169] [util.py:216]               [INFO]     |                                     Exiting Plex Meta Manager                                      |
[2022-11-05 19:23:30,169] [util.py:220]               [INFO]     |====================================================================================================|
